;(**** end of print gcode ****)
M140 S0        ;(Set heated bed temperature to 0)
M104 S0 T0     ;(Set extruder 0 temperature to 0)
M104 S0 T1     ;(Set extruder 1 temperature to 0)
M127 T0        ;(Disable cooling fan)
G1 Z150 F900   ;(Move the platform down)
G162 X Y F2000 ;(Home X and Y)
M18 X Y Z      ;(Turn off steppers after a build)
M18 A B        ;(Turn off A and B steppers)
M70 P5         ;(Display We <3 Making Things!)
M72 P1         ;(Play Ta-Da song )
M73 P100       ;(Set build percentage to 100%)
M137           ;(build end notification)
;(**** end of end of print gcode ****)