;START_OF_HEADER
;HEADER_VERSION:0.1
;FLAVOR:Griffin
;GENERATOR.NAME:IceSL
;GENERATOR.VERSION:2.1
;GENERATOR.BUILD_DATE:2017-07-28
;TARGET_MACHINE.NAME:Ultimaker 3

;EXTRUDER_TRAIN.0.INITIAL_TEMPERATURE:<TOOLTEMP0>

;EXTRUDER_TRAIN.0.MATERIAL.VOLUME_USED:<TOOLVOLUME0>
;EXTRUDER_TRAIN.0.MATERIAL.GUID:<TOOLMATERIAL0>
;EXTRUDER_TRAIN.0.NOZZLE.DIAMETER:0.4

;EXTRUDER_TRAIN.1.INITIAL_TEMPERATURE:<TOOLTEMP1>

;EXTRUDER_TRAIN.1.MATERIAL.VOLUME_USED:<TOOLVOLUME1>
;EXTRUDER_TRAIN.1.MATERIAL.GUID:<TOOLMATERIAL1>
;EXTRUDER_TRAIN.1.NOZZLE.DIAMETER:0.4

;BUILD_PLATE.INITIAL_TEMPERATURE:<HBPTEMP>

;PRINT.TIME:<ESTPTIME>

;PRINT.SIZE.MIN.X:<XMIN>
;PRINT.SIZE.MIN.Y:<YMIN>
;PRINT.SIZE.MIN.Z:<ZMIN>
;PRINT.SIZE.MAX.X:<XMAX>
;PRINT.SIZE.MAX.Y:<YMAX>
;PRINT.SIZE.MAX.Z:<ZMAX>
;END_OF_HEADER
